#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

Red='\033[0;31m'
Green='\033[0;32m'
message="There is something wrong with your branch name. Branch names in this project must adhere to this format: TEAM-{NUMBER} or AP-{NUMBER} or Release/{env-date} . Your commit will be rejected. You should rename your branch to a valid name and try again."

echo "${Green}Checking Working Branch ..."
if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
    echo ""
    echo "${Red}Your current branch is Restricted, please create branch based on your Jira Ticket"
    echo ""
    exit 1
fi

npx lint-staged --relative
